foreground #FDFBD8
background #1F1617
cursor #CDB58A

active_tab_foreground #1F1617
active_tab_background #AE9FD0
inactive_tab_foreground #FDFBD8
inactive_tab_background #4D4041

active_border_color #AE9FD0
inactive_border_color #ABA985
bell_border_color #B05D8E

color0 #4D4041
color1 #B05D8E
color2 #957A5D
color3 #CC4055
color4 #887EA1
color5 #B79587
color6 #BCB76B
color7 #F4F1BF
color8 #ABA985
color9 #D358A1
color10 #A77C50
color11 #FC2243
color12 #AE9FD0
color13 #F4C6B4
color14 #FAF48F
color15 #F4F1BF
