foreground         #FFF2F2
background         #00000A
cursor             #8FCDBD

active_tab_foreground     #00000A
active_tab_background     #FFF2F2
inactive_tab_foreground   #FFF2F2
inactive_tab_background   #00000A

active_border_color   #FFF2F2
inactive_border_color #00000A
bell_border_color     #9B7574

color0      #00000A
color1		#9B7574
color2		#1FA787
color3		#CA8E1D
color4		#BCD7EC
color5		#E2E6B9
color6		#BCD7EC
color7		#F6E4E4
color8		#ACA0A0
color9		#9B7574
color10		#1FA787
color11		#CA8E1D
color12		#BCD7EC
color13		#E2E6B9
color14		#BCD7EC
color15		#F6E4E4
