foreground #D7FFFF
background #1B1821
cursor #B9B7AE

active_tab_foreground #1B1821
active_tab_background #8DFFFF
inactive_tab_foreground #85ADAD
inactive_tab_background #46434F

active_border_color #8DFFFF
inactive_border_color #85ADAD
bell_border_color #A3578A

color0 #46434F
color1 #A3578A
color2 #947A70
color3 #7785B1
color4 #B08952
color5 #B2959C
color6 #6ABFBF
color7 #BEF7F7
color8 #85ADAD
color9 #C661A5
color10 #A57C6E
color11 #8097DB
color12 #EBB76D
color13 #EDC6D0
color14 #8DFFFF
color15 #BEF7F7
